### ISSUE TITLE
请问下这种api是怎么部署到服务器上面的？

### ISSUE THREAD

**Issue by tumoxuese** [jwenjian/awesome-qrcode#2]
请问下这种api是怎么部署到服务器上面的？
https://wenjian.pythonanywhere.com/qrcode/picture

我把vue的代码放到服务器上面，但不能生成二维码，qrcode/normal/ 404
有没有啥操作步骤的，谢谢。

**Comment by jwenjian** [comment]
@tumoxuese 

只部署vue代码是没有办法生成二维码的， 实际的生成工作是由python代码完成并提供了API供vue代码调用。

页面工程和python工程(当前工程)配合才可以。

python项目目前是人工部署在 [pythonanywhere.com](pythonanywhere.com) 上面的， 这是一个免费托管python应用的地方。

**Comment by tumoxuese** [comment]
好的，谢谢。
